import { allProducts,seedProducts } from "@/lib/catalog";
const stories=[
  {slug:"new-nigerian-luxury",title:"The New Nigerian Luxury Movement",dek:"A new generation is defining luxury through confident colour, considered craft and clothes made for real Nigerian life.",body:"Contemporary Nigerian luxury is not one fixed visual language. It moves between restraint and celebration, tailoring and ease, global references and local instinct. What connects the strongest work is intention: fabric chosen for climate, silhouettes built for movement and pieces with a life beyond one photograph."},
  {slug:"style-ankara",title:"5 Ways To Style Ankara Without Looking Traditional",dek:"Let proportion and one decisive print do the work.",body:"Start with a clean silhouette. Pair one printed piece with quiet tailoring, repeat one colour from the fabric in a shoe or bag, and leave space around statement jewellery. The aim is not to reduce Ankara—it is to give the textile enough visual room to lead."},
  {slug:"behind-collection",title:"Behind The Collection",dek:"From first line to final fitting.",body:"Every piece begins with the body in motion. The process moves from proportion studies to fabric tests, fittings and small adjustments that change how a garment feels when walking, sitting or dancing."},
  {slug:"lagos-fashion",title:"How Lagos Fashion Is Changing",dek:"Personal style is becoming the city’s most persuasive runway.",body:"Lagos style has always been expressive. The shift is in how quickly people now move between made-to-measure, independent labels, vintage finds and international references—building wardrobes that feel individual rather than prescribed."},
  {slug:"modern-elegance",title:"Modern African Elegance",dek:"Less costume. More point of view.",body:"Modern elegance is not defined by one fabric or motif. It is found in the precision of a shoulder, the confidence of a colour decision and the ease with which a piece belongs to the wearer."}
];
export const dynamic="force-dynamic";
export default async function Journal(){let products=seedProducts;try{products=await allProducts()}catch{}return <main className="journal-page"><header><span>VELMORA / JOURNAL</span><h1>Fashion,<br/><em>in context.</em></h1><p>Editorial notes on the ideas, makers and styling choices shaping contemporary African fashion.</p></header><section className="journal-feature"><img src={products[3]?.image||products[0].image} alt="VELMORA editorial"/><div><span>ISSUE 01 / 2026</span><h2>{stories[0].title}</h2><p>{stories[0].dek}</p><a href={`#${stories[0].slug}`}>Read story ↓</a></div></section><section className="journal-articles">{stories.map((story,i)=><article id={story.slug} key={story.slug}><div><span>0{i+1}</span><h2>{story.title}</h2><p className="journal-dek">{story.dek}</p></div><p>{story.body}</p></article>)}</section></main>}
