import Link from "next/link";
import { env } from "cloudflare:workers";
import { getChatGPTUser,chatGPTSignInPath,chatGPTSignOutPath } from "@/app/chatgpt-auth";
import { naira } from "@/lib/catalog";
export const dynamic="force-dynamic";
type Order={id:string;created_at:string;status:string;total:number;state:string};
export default async function Account(){const user=await getChatGPTUser();if(!user)return <main className="account-signin"><div className="account-photo"><img src="/indigo.png" alt="Velmora indigo dress"/></div><div><span className="eyebrow">VELMORA / YOUR ACCOUNT</span><h1>WELCOME BACK</h1><p>Sign in to see your orders and saved pieces.</p><a className="dark-button" href={chatGPTSignInPath("/account")} target="_top">SIGN IN WITH CHATGPT</a><Link className="continue-link" href="/shop">Continue shopping</Link></div></main>;
  let orders:Order[]=[];try{const result=await env.DB!.prepare("SELECT id,created_at,status,total,state FROM orders WHERE user_id=? ORDER BY created_at DESC LIMIT 20").bind(user.userId).all<Order>();orders=result.results}catch{}
  return <main className="account-page"><aside><span className="eyebrow">VELMORA / ACCOUNT</span><h1>MY ACCOUNT</h1><p>Good to see you, {user.fullName?.split(" ")[0]||"there"}.</p><nav><a href="#orders">Orders</a><Link href="/saved">Saved pieces</Link><a href={chatGPTSignOutPath("/")} target="_top">Sign out</a></nav></aside><section id="orders"><h2>RECENT ORDERS</h2>{orders.length?orders.map(order=><article className="account-order" key={order.id}><div><span className="eyebrow">ORDER / {order.id}</span><h3>{naira(order.total)}</h3><p>{new Date(order.created_at).toLocaleDateString("en-NG",{dateStyle:"long"})} · {order.state}</p></div><span className="status-tag">{order.status}</span></article>):<div className="empty-state"><h3>No orders yet.</h3><p>Your order requests will appear here.</p><Link className="text-link" href="/shop">SHOP THE COLLECTION ↗</Link></div>}<div className="account-saved"><h2>SAVED PIECES</h2><p>Keep an edit of the styles you love.</p><Link className="text-link" href="/saved">VIEW SAVED PIECES ↗</Link></div></section></main>}
