"use client";
import { useState } from "react";
import { type Product, naira } from "@/lib/shared";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";
type Order={id:string;full_name:string;email:string;created_at:string;total:number;status:string;state:string};
export function AdminOrders({initial}:{initial:Order[]}){const [orders,setOrders]=useState(initial);const [error,setError]=useState("");async function update(id:string,status:string){const response=await fetch("/api/admin/orders",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status})});if(response.ok)setOrders(current=>current.map(o=>o.id===id?{...o,status}:o));else setError("Could not update this order.")}
  return <><div className="admin-title"><div><span className="eyebrow">VELMORA / OPERATIONS</span><h1>Orders</h1><p>Review and manage order requests.</p></div><strong>{orders.length} orders</strong></div>{error&&<p role="alert" className="field-error">{error}</p>}<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>ORDER</th><th>CUSTOMER</th><th>DATE</th><th>STATE</th><th>TOTAL</th><th>STATUS</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td><strong>{o.id}</strong></td><td>{o.full_name}<small>{o.email}</small></td><td>{new Date(o.created_at).toLocaleDateString("en-NG")}</td><td>{o.state}</td><td>{naira(o.total)}</td><td><Select value={o.status} onValueChange={v=>update(o.id,v)}><SelectTrigger aria-label={`Status for ${o.id}`}><SelectValue/></SelectTrigger><SelectContent>{["Requested","Processing","Dispatched","Completed","Cancelled"].map(s=><SelectItem value={s} key={s}>{s}</SelectItem>)}</SelectContent></Select></td></tr>)}</tbody></table>{!orders.length&&<div className="empty-state">No orders yet.</div>}</div></>}
export function AdminProducts({initial}:{initial:Product[]}){const [products,setProducts]=useState(initial);const [saving,setSaving]=useState("");const [error,setError]=useState("");async function update(product:Product,changes:Partial<Product>){const next={...product,...changes};setSaving(product.id);const response=await fetch("/api/admin/products",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:next.id,stock:next.stock,price:next.price,active:next.active})});if(response.ok)setProducts(current=>current.map(p=>p.id===next.id?next:p));else setError("Could not save product changes.");setSaving("")}
  return <><div className="admin-title"><div><span className="eyebrow">VELMORA / OPERATIONS</span><h1>Products</h1><p>Manage price, availability, and stock.</p></div><strong>{products.length} pieces</strong></div>{error&&<p role="alert" className="field-error">{error}</p>}<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>PRODUCT</th><th>CATEGORY</th><th>PRICE (₦)</th><th>STOCK</th><th>STATUS</th><th>ACTION</th></tr></thead><tbody>{products.map(p=><ProductRow key={p.id} product={p} saving={saving===p.id} update={update}/>)}</tbody></table></div></>}
function ProductRow({product:p,saving,update}:{product:Product;saving:boolean;update:(p:Product,changes:Partial<Product>)=>Promise<void>}){const [price,setPrice]=useState(String(p.price));const [stock,setStock]=useState(String(p.stock));return <tr><td className="admin-product"><img src={p.image} alt=""/><span><strong>{p.name}</strong><small>{p.color}</small></span></td><td>{p.category}</td><td><input aria-label={`${p.name} price`} type="number" min="1000" max="10000000" value={price} onChange={e=>setPrice(e.target.value)}/></td><td><input aria-label={`${p.name} stock`} type="number" min="0" max="100000" value={stock} onChange={e=>setStock(e.target.value)}/></td><td><Select value={p.active?"active":"hidden"} onValueChange={v=>update(p,{active:v==="active"?1:0})}><SelectTrigger aria-label={`${p.name} visibility`}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="active">Active</SelectItem><SelectItem value="hidden">Hidden</SelectItem></SelectContent></Select></td><td><button disabled={saving} onClick={()=>update(p,{price:Number(price),stock:Number(stock)})}>{saving?"Saving":"Save"}</button></td></tr>}
