/* Browser storage and URL state are restored after mount to preserve the server hydration snapshot. */
/* eslint-disable react-hooks/set-state-in-effect */
"use client";
import { ChangeEvent, useEffect, useMemo, useState } from "react";
import { ArrowRight, Bookmark, Camera, Check, Heart, Rotate3D, Search } from "lucide-react";
import type { Product } from "@/lib/shared";
import { naira } from "@/lib/shared";
import { useStore } from "./store-provider";

const occasions=["Wedding","Work","Casual","Date Night","Birthday","Detty December","Eid","Graduation"];
const silhouettes=["Relaxed","Fitted","Oversized","Elegant silhouette"];
const personalities=["Minimal","Luxury","Streetwear","African Contemporary","Classic","Bold Fashion"];
const settings=["Lagos wedding","Office event","Beach vacation","Evening party"];
const colours=["Original","Emerald","Black","Champagne","Burgundy"];
const accessories={shoes:["Gold heels","Sculptural sandals","Leather loafers"],bag:["Pearl mini bag","Soft leather clutch","Woven top-handle"],jewellery:["Gold drop earrings","Pearl studs","Sculptural cuff"],hair:["Elegant updo","Soft natural curls","Sleek low bun"]};

export function FashionLab({products}:{products:Product[]}){
  const {add}=useStore();
  const [occasion,setOccasion]=useState("Wedding"),[silhouette,setSilhouette]=useState("Elegant silhouette"),[personality,setPersonality]=useState("Luxury"),[setting,setSetting]=useState("Lagos wedding"),[budget,setBudget]=useState(100000),[request,setRequest]=useState("");
  const [recommendation,setRecommendation]=useState<Product|null>(null),[photo,setPhoto]=useState(""),[colour,setColour]=useState("Original"),[look,setLook]=useState({shoes:0,bag:0,jewellery:0,hair:0}),[saved,setSaved]=useState<string[]>([]),[fit,setFit]=useState("M"),[notice,setNotice]=useState("");
  const dresses=products.filter(p=>p.category==="Dresses");
  const chosen=recommendation||dresses.find(p=>p.slug==="adaeze-maxi-dress")||dresses[0]||products[0];
  const ranked=useMemo(()=>dresses.filter(p=>p.price<=budget).sort((a,b)=>{
    const wantDark=personality==="Luxury"||occasion==="Date Night"; const score=(p:Product)=>(wantDark&&["Wine","Forest","Indigo"].includes(p.color)?2:0)+(silhouette.includes("Elegant")&&p.description.toLowerCase().includes("drap")?2:0)+(setting.includes("Beach")&&p.price<80000?1:0);return score(b)-score(a);
  }),[dresses,budget,personality,occasion,silhouette,setting]);
  useEffect(()=>{try{setSaved(JSON.parse(localStorage.getItem("velmora-boards")||"[]"))}catch{}},[]);
  function styleMe(){const q=request.toLowerCase();const colourMatch=dresses.find(p=>q.includes(p.color.toLowerCase())&&p.price<=budget);const next=colourMatch||ranked[0]||[...dresses].sort((a,b)=>a.price-b.price)[0]||products[0];setRecommendation(next);document.getElementById("stylist-result")?.scrollIntoView({behavior:"smooth",block:"center"})}
  function upload(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(file){if(photo)URL.revokeObjectURL(photo);setPhoto(URL.createObjectURL(file))}}
  function saveLook(){if(!chosen)return;const next=Array.from(new Set([...saved,chosen.slug]));setSaved(next);localStorage.setItem("velmora-boards",JSON.stringify(next));setNotice("Saved to My Luxury Wardrobe");setTimeout(()=>setNotice(""),2400)}
  function estimate(form:FormData){const bust=Number(form.get("bust")),waist=Number(form.get("waist"));const measure=Math.max(bust,waist+20);setFit(measure<86?"S":measure<96?"M":measure<106?"L":"XL")}
  if(!chosen)return null;
  return <main className="fashion-lab">
    <section className="lab-toolbar"><div><span className="lab-kicker">VELMORA FASHION LAB</span><h1>Find your perfect look.</h1></div><nav aria-label="Fashion experiences"><a href="#stylist">Stylist</a><a href="#try-on">Try-on</a><a href="#studio">Outfit studio</a><a href="/closet">My Closet</a></nav></section>

    <section className="stylist-workspace" id="stylist">
      <div className="smart-style-search"><Search size={20}/><label><span>Ask the stylist in your own words</span><input value={request} onChange={e=>setRequest(e.target.value)} placeholder="I need an elegant dress for a Lagos wedding under ₦100,000"/></label><button onClick={styleMe}>Style me <ArrowRight size={16}/></button></div>
      <div className="lab-section-head"><span>01 / PERSONAL STYLIST</span><h2>Refine your direction.</h2></div>
      <div className="stylist-grid"><div className="stylist-controls">
        <Choice title="Occasion" options={occasions} value={occasion} change={setOccasion}/><Choice title="Preferred fit" options={silhouettes} value={silhouette} change={setSilhouette}/><Choice title="Style personality" options={personalities} value={personality} change={setPersonality}/><Choice title="Setting" options={settings} value={setting} change={setSetting}/>
        <label className="budget-control"><span>Budget</span><strong>{naira(budget)}</strong><input aria-label="Budget" type="range" min="50000" max="120000" step="5000" value={budget} onChange={e=>setBudget(Number(e.target.value))}/></label>
        <button className="lab-primary" onClick={styleMe}><ArrowRight size={17}/> Create my look</button>
      </div><article className="stylist-result" id="stylist-result"><div className="result-image"><img src={chosen.image} alt={chosen.name}/><span>{chosen.color} / {chosen.category}</span></div><div className="result-copy"><span className="lab-kicker">YOUR EDIT</span><h3>{chosen.name}</h3><b>{naira(chosen.price)}</b><p>For your {setting.toLowerCase()}, we selected the {chosen.name} with {accessories.shoes[look.shoes].toLowerCase()}, a {accessories.bag[look.bag].toLowerCase()} and {accessories.jewellery[look.jewellery].toLowerCase()}. The {silhouette.toLowerCase()} direction keeps the look {personality.toLowerCase()} without feeling overworked.</p><ul><li>{accessories.shoes[look.shoes]}</li><li>{accessories.bag[look.bag]}</li><li>{accessories.jewellery[look.jewellery]}</li><li>{accessories.hair[look.hair]}</li></ul><div className="result-actions"><a href={`/product/${chosen.slug}`}>Explore the piece <ArrowRight size={16}/></a><button onClick={saveLook}><Bookmark size={15}/> Save look</button></div>{notice&&<small className="lab-notice"><Check size={14}/>{notice}</small>}</div></article></div>
      <div className="lab-dress-picker"><div><span>CHOOSE ANOTHER PIECE</span><small>{dresses.length} dresses available</small></div><div>{dresses.map(p=><button className={p.id===chosen.id?"active":""} onClick={()=>setRecommendation(p)} key={p.id}><img src={p.image} alt=""/><span>{p.name}</span><b>{naira(p.price)}</b></button>)}</div></div>
    </section>

    <section className="tryon-section" id="try-on"><div className="lab-section-head light"><span>02 / VIRTUAL FITTING ROOM</span><h2>Compare before you choose.</h2><p>Your photo stays in this browser and is not uploaded.</p></div><div className="tryon-grid"><div className="tryon-stage">{photo?<><img src={photo} alt="Your uploaded preview"/><button className="replace-photo" onClick={()=>setPhoto("")}>Replace photo</button></>:<label><Camera size={34}/><strong>Add your photo</strong><span>Full-length photos work best</span><input type="file" accept="image/*" onChange={upload}/></label>}<span className="preview-label">YOUR PHOTO</span></div><div className={`tryon-stage garment colour-${colour.toLowerCase().replace(" ","-")}`}><img src={chosen.image} alt={`${chosen.name} preview`}/><span className="preview-label">{chosen.name.toUpperCase()} / {colour.toUpperCase()}</span></div></div><div className="colour-picker" aria-label="Preview colours">{colours.map(c=><button className={colour===c?"active":""} key={c} onClick={()=>setColour(c)}>{c}</button>)}</div><div className="tryon-actions"><button className="lab-primary" onClick={()=>document.getElementById("studio")?.scrollIntoView({behavior:"smooth"})}>Style this version <ArrowRight size={16}/></button><p>Interactive colour and side-by-side comparison are live. Photorealistic garment transfer needs a connected image-generation service.</p></div></section>

    <section className="outfit-studio" id="studio"><div className="lab-section-head"><span>03 / OUTFIT STUDIO</span><h2>Build the whole story.</h2></div><div className="studio-grid"><div className="studio-visual"><img src={chosen.image} alt={chosen.name}/><div className="floating-piece one">{accessories.shoes[look.shoes]}</div><div className="floating-piece two">{accessories.bag[look.bag]}</div><div className="floating-piece three">{accessories.jewellery[look.jewellery]}</div></div><div className="studio-options"><h3>{chosen.name}</h3><StudioRow title="Shoes" items={accessories.shoes} active={look.shoes} pick={n=>setLook({...look,shoes:n})}/><StudioRow title="Bag" items={accessories.bag} active={look.bag} pick={n=>setLook({...look,bag:n})}/><StudioRow title="Jewellery" items={accessories.jewellery} active={look.jewellery} pick={n=>setLook({...look,jewellery:n})}/><StudioRow title="Hair" items={accessories.hair} active={look.hair} pick={n=>setLook({...look,hair:n})}/><div className="studio-total"><span>Available now</span><strong>{chosen.name} · {naira(chosen.price)}</strong><small>Accessories are styling references and are not added to the charge.</small></div><button className="lab-primary" onClick={()=>{add(chosen,fit);setNotice(`${chosen.name} added in ${fit}`)}}>Add available piece · {fit}</button><button className="lab-secondary" onClick={saveLook}><Heart size={15}/> Save complete styling board</button></div></div></section>

    <section className="fit-and-view"><div className="fit-card"><span>SIZE PREDICTION / BETA</span><h2>Your best fit.</h2><form action={estimate}><label>Bust (cm)<input name="bust" type="number" defaultValue="92" min="60" max="160"/></label><label>Waist (cm)<input name="waist" type="number" defaultValue="74" min="50" max="150"/></label><button>Predict size</button></form><strong className="fit-result">Recommended: {fit}</strong><p>A fit estimate based on your measurements. Check the size guide before ordering.</p></div><div className="viewer-card"><span>INTERACTIVE VIEW / CONCEPT</span><Rotate3D size={31}/><h2>Move with the piece.</h2><div className="mini-viewer"><img src={chosen.image} alt={chosen.name}/></div><p>Move your pointer across the image to inspect its silhouette. Full 360° garment capture can replace this study when product spins are available.</p></div></section>

    <section className="experience-directory"><a href="/journal"><span>VELMORA JOURNAL</span><strong>Read fashion in context.</strong><ArrowRight/></a><a href="/fashion-show"><span>COLLECTION 2026</span><strong>Enter the runway.</strong><ArrowRight/></a><a href="/community"><span>STYLE GALLERY</span><strong>See how the community wears it.</strong><ArrowRight/></a><a href="/closet"><span>MY CLOSET</span><strong>{saved.length} saved look{saved.length===1?"":"s"} on this device.</strong><ArrowRight/></a></section>
  </main>
}

function Choice({title,options,value,change}:{title:string;options:string[];value:string;change:(v:string)=>void}){return <fieldset><legend>{title}</legend><div>{options.map(o=><button type="button" className={value===o?"active":""} onClick={()=>change(o)} key={o}>{o}</button>)}</div></fieldset>}
function StudioRow({title,items,active,pick}:{title:string;items:string[];active:number;pick:(n:number)=>void}){return <fieldset><legend>{title}</legend>{items.map((item,i)=><button type="button" className={i===active?"active":""} onClick={()=>pick(i)} key={item}>{item}{i===active&&<Check size={13}/>}</button>)}</fieldset>}
