"use client";
import { useState } from "react";
import { useHydrated } from "@/lib/hydration";
export type PublicReview={id:string;display_name:string;rating:number;body:string;created_at:string};
export function ProductReviews({productId,reviews}:{productId:string;reviews:PublicReview[]}){
  const [rating,setRating]=useState(5);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const hydrated=useHydrated();
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const form=e.currentTarget;const data=new FormData(form);try{const response=await fetch("/api/reviews",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({productId,rating,orderId:data.get("orderId"),email:data.get("email"),displayName:data.get("displayName"),body:data.get("body")})});const result=await response.json() as {error?:string;message?:string};setMessage(result.message||result.error||"Could not submit the review.");if(response.ok)form.reset()}catch{setMessage("Could not submit the review. Please try again.")}finally{setBusy(false)}}
  return <section className="product-reviews" id="reviews"><div><span className="eyebrow">CUSTOMER REVIEWS</span><h2>Worn by you.</h2>{reviews.length?<div className="review-list">{reviews.map(review=><article key={review.id}><div><strong>{review.display_name}</strong><span>{"★".repeat(review.rating)}{"☆".repeat(5-review.rating)}</span></div><p>{review.body}</p><small>{new Date(review.created_at).toLocaleDateString("en-NG",{year:"numeric",month:"long"})}</small></article>)}</div>:<p className="review-empty">No customer reviews yet.</p>}</div><form onSubmit={submit}><h3>Review this piece</h3><p>Use the email and reference from your order request. Reviews are checked before appearing here.</p><fieldset><legend>Rating</legend><div className="rating-options">{[1,2,3,4,5].map(n=><button type="button" key={n} onClick={()=>setRating(n)} className={rating===n?"selected":""} aria-label={`${n} star${n===1?"":"s"}`} aria-pressed={rating===n}>{n} ★</button>)}</div></fieldset><label>Your name<input required name="displayName" minLength={2} maxLength={50}/></label><label>Order email<input required name="email" type="email" autoComplete="email"/></label><label>Order reference<input required name="orderId"/></label><label>Your review<textarea required name="body" minLength={15} maxLength={500} rows={4}/></label><button className="v2-button" type="submit" disabled={!hydrated||busy}>{busy?"Sending…":"Submit review"}</button>{message&&<p role="status" className="review-message">{message}</p>}</form></section>
}
