"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { type Product, naira,sizes } from "@/lib/shared";
import { useHydrated } from "@/lib/hydration";
import { useStore } from "./store-provider";
import { RadioGroup,RadioGroupItem } from "@/components/ui/radio-group";
import { Accordion,AccordionContent,AccordionItem,AccordionTrigger } from "@/components/ui/accordion";
export function PurchasePanel({product}:{product:Product}){const [size,setSize]=useState("");const [error,setError]=useState("");const {add}=useStore();const router=useRouter();const hydrated=useHydrated();function addToBag(){if(!size){setError("Choose a size to continue.");return}add(product,size);router.push("/bag")}
  return <div className="purchase-panel"><span className="eyebrow">VELMORA / {product.category.toUpperCase()}</span><h1>{product.name}</h1><div className="pdp-price">{naira(product.price)}</div><p className="pdp-description">{product.description}</p><div className="purchase-divider"/><div className="option-label">COLOUR: {product.color.toUpperCase()}</div><span className={`swatch ${product.color.toLowerCase()}`} title={product.color}/><div className="size-heading"><span className="option-label">SIZE</span><Link href="/size-guide">Size guide ↗</Link></div><RadioGroup value={size} onValueChange={value=>{setSize(value);setError("")}} className="size-grid" aria-label="Select size" disabled={!hydrated}>{sizes.map(s=><label key={s} className={`size-option ${size===s?"selected":""}`}><RadioGroupItem value={s} className="sr-only"/>{s}</label>)}</RadioGroup>{error&&<p role="alert" className="field-error">{error}</p>}<button className="dark-button" disabled={product.stock===0||!hydrated} onClick={addToBag}>{product.stock===0?"SOLD OUT":"ADD TO BAG"}</button><div className="purchase-notes"><span>Delivery across Nigeria</span></div><Accordion type="single" collapsible className="pdp-accordion"><AccordionItem value="details"><AccordionTrigger>PRODUCT DETAILS</AccordionTrigger><AccordionContent>{product.description}</AccordionContent></AccordionItem><AccordionItem value="fit"><AccordionTrigger>SIZE & CARE</AccordionTrigger><AccordionContent>See the size guide for measurements and follow the care label inside the garment.</AccordionContent></AccordionItem><AccordionItem value="delivery"><AccordionTrigger>DELIVERY & RETURNS</AccordionTrigger><AccordionContent>Delivery rates are shown at checkout. See delivery and returns for more information.</AccordionContent></AccordionItem></Accordion></div>
}
