"use client";
import { useMemo, useState } from "react";
import type { Product } from "@/lib/shared";
import { useHydrated } from "@/lib/hydration";
import { ProductCard } from "./product-card";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";
export function ShopClient({products,initialCategory="All",query="",searchPage=false}:{products:Product[];initialCategory?:string;query?:string;searchPage?:boolean}){
  const [category,setCategory]=useState(initialCategory);const [color,setColor]=useState("All");const [sort,setSort]=useState("featured");const [search,setSearch]=useState(query);
  const hydrated=useHydrated();
  const intent=useMemo(()=>{const q=search.toLowerCase();const namedColor=products.find(p=>q.includes(p.color.toLowerCase()))?.color;const dark=/black|dark|evening|date night/.test(q);const maxMatch=q.match(/(?:under|below|budget)\s*(?:₦|ngn)?\s*([\d,]+)/);const max=maxMatch?Number(maxMatch[1].replaceAll(",","")):null;const wantsDress=/dress|wedding|party|date|eid|graduation/.test(q);return {namedColor,dark,max,wantsDress,occasion:/wedding/.test(q)?"Wedding":/work|office/.test(q)?"Work":/date/.test(q)?"Date night":/eid/.test(q)?"Eid":null}},[search,products]);
  const filtered=useMemo(()=>{let list=products.filter(p=>(category==="All"||p.category===category)&&(color==="All"||p.color===color));if(searchPage&&search.trim()){const q=search.toLowerCase();let smart=list.filter(p=>(!intent.wantsDress||p.category==="Dresses")&&(!intent.max||p.price<=intent.max)&&(!intent.namedColor||p.color===intent.namedColor)&&(!intent.dark||["Wine","Forest","Indigo"].includes(p.color)));if(!smart.length)smart=list.filter(p=>(!intent.wantsDress||p.category==="Dresses")&&(!intent.max||p.price<=intent.max));list=smart.length?smart:list.filter(p=>`${p.name} ${p.category} ${p.color}`.toLowerCase().includes(q))}if(sort==="low")list=[...list].sort((a,b)=>a.price-b.price);if(sort==="high")list=[...list].sort((a,b)=>b.price-a.price);return list},[products,category,color,sort,search,searchPage,intent]);
  return <main className="catalog-page"><div className="catalog-heading"><div><span className="eyebrow">VELMORA / THE COLLECTION</span><h1>{searchPage?"SMART SEARCH":category==="All"?"THE COLLECTION":category.toUpperCase()}</h1><p>{searchPage?"Describe the occasion, colour, mood and budget.":"Made to move with you."}</p></div>{searchPage&&<label className="search-field smart-search-field"><span className="sr-only">Describe what you need</span><input autoFocus disabled={!hydrated} value={search} onChange={e=>setSearch(e.target.value)} placeholder="A classy dark dress for a Lagos wedding under ₦100,000"/></label>}</div>{searchPage&&search.trim()&&<div className="search-intent"><span>UNDERSTOOD</span>{intent.occasion&&<b>{intent.occasion}</b>}{intent.wantsDress&&<b>Dresses</b>}{intent.namedColor&&<b>{intent.namedColor}</b>}{intent.dark&&!intent.namedColor&&<b>Dark tones</b>}{intent.max&&<b>Up to {new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:0}).format(intent.max)}</b>}<small>{filtered.length} recommendation{filtered.length===1?"":"s"}</small></div>}
    <div className="filter-row"><div className="filter-controls"><Filter label="Category" value={category} onChange={setCategory} options={["All","Dresses","Sets","Tops"]} disabled={!hydrated}/><Filter label="Colour" value={color} onChange={setColor} options={["All",...Array.from(new Set(products.map(p=>p.color)))]} disabled={!hydrated}/></div><div className="sort-controls"><span>{filtered.length} pieces</span><Filter label="Sort" value={sort} onChange={setSort} options={["featured","low","high"]} titles={{featured:"Featured",low:"Price: low to high",high:"Price: high to low"}} disabled={!hydrated}/></div></div>
    {filtered.length?<div className="catalog-grid">{filtered.map(p=><ProductCard key={p.id} product={p}/>)}</div>:<div className="empty-state"><h2>No pieces found.</h2><p>Try another search or clear the filters.</p><button disabled={!hydrated} onClick={()=>{setCategory("All");setColor("All");setSearch("")}}>SHOW ALL PIECES</button></div>}
  </main>
}
function Filter({label,value,onChange,options,titles={},disabled=false}:{label:string;value:string;onChange:(v:string)=>void;options:string[];titles?:Record<string,string>;disabled?:boolean}){return <div className="filter-select"><span>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger disabled={disabled} aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o} value={o}>{titles[o]||o}</SelectItem>)}</SelectContent></Select></div>}
