"use client";
import { useEffect, useState } from "react";
import { ArrowRight, Bot, MessageCircleMore, Sparkles } from "lucide-react";
import { Sheet,SheetContent,SheetDescription,SheetHeader,SheetTitle,SheetTrigger } from "@/components/ui/sheet";
import { useHydrated } from "@/lib/hydration";
type ProductLink={name:string;price:string;slug:string};type Message={role:"user"|"assistant";text:string;products?:ProductLink[]};
export function StyleChat(){const [mode,setMode]=useState<"ai"|"guide">("guide");const [messages,setMessages]=useState<Message[]>([]);const [text,setText]=useState("");const [busy,setBusy]=useState(false);const hydrated=useHydrated();useEffect(()=>{fetch("/api/style-chat").then(r=>r.json() as Promise<{mode?:string}>).then(data=>setMode(data.mode==="ai"?"ai":"guide")).catch(()=>{})},[]);
  async function send(e:React.FormEvent){e.preventDefault();const question=text.trim();if(!question||busy)return;setText("");setMessages(list=>[...list,{role:"user",text:question}]);setBusy(true);try{const response=await fetch("/api/style-chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:question})});const data=await response.json() as {reply?:string;mode?:"ai"|"guide";products?:ProductLink[]};setMessages(list=>[...list,{role:"assistant",text:data.reply||"Please try again.",products:data.products}]);if(data.mode)setMode(data.mode)}catch{setMessages(list=>[...list,{role:"assistant",text:"Could not connect. Please try again."}])}finally{setBusy(false)}}
  return <Sheet><SheetTrigger className="chat-trigger ai-chat-trigger" disabled={!hydrated}><span className="ai-chat-icon"><MessageCircleMore size={22}/><b>AI</b></span><span><strong>VEROLA AI</strong><small>Your fashion assistant</small></span></SheetTrigger><SheetContent side="right" className="style-chat-sheet ai-chat-sheet"><SheetHeader><div className="ai-chat-brand"><span><Bot size={24}/></span><div><SheetTitle>VEROLA AI</SheetTitle><SheetDescription>Personal fashion assistant</SheetDescription></div><i>ONLINE</i></div></SheetHeader><div className="chat-messages" aria-live="polite">{messages.length?messages.map((m,i)=><div className={`chat-message ${m.role}`} key={i}><p>{m.text}</p>{m.role==="assistant"&&m.products&&<div className="chat-links">{m.products.map(p=><a key={p.slug} href={`/product/${p.slug}`}>{p.name} · {p.price}<ArrowRight size={15}/></a>)}</div>}</div>):<div className="ai-welcome"><span><Sparkles size={18}/></span><div><strong>Hi, I’m Verola AI.</strong><p>How can I help you today? Tell me the occasion, colour, size or budget you have in mind.</p></div><div className="chat-suggestions"><button onClick={()=>setText("Find me a wedding guest dress under ₦90,000")}>Wedding look under ₦90k</button><button onClick={()=>setText("Which dress works for an evening party?")}>Evening party look</button><button onClick={()=>setText("Help me choose my size")}>Help with sizing</button></div></div>}{busy&&<p role="status" className="chat-pending">Verola is styling your answer…</p>}</div><form onSubmit={send} className="chat-form"><label className="sr-only" htmlFor="style-question">Message Verola AI</label><input id="style-question" value={text} onChange={e=>setText(e.target.value)} maxLength={300} placeholder="Message Verola AI…"/><button type="submit" disabled={busy||!text.trim()} aria-label="Send message"><ArrowRight size={19}/></button></form></SheetContent></Sheet>
}
