"use client";
import { useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { useStore } from "@/components/store-provider";
import { naira } from "@/lib/shared";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";
import { RadioGroup,RadioGroupItem } from "@/components/ui/radio-group";
const states=["Lagos","Abuja (FCT)","Ogun","Oyo","Rivers","Kano","Enugu","Anambra","Delta","Edo","Kaduna","Other state"];
export default function Checkout(){const {items,subtotal,ready,clear}=useStore();const router=useRouter();const [state,setState]=useState("Lagos");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [demo,setDemo]=useState(false);useEffect(()=>setDemo(new URLSearchParams(location.search).get("demo")==="1"),[]);const deliveryFee=state==="Lagos"?3500:5500;
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(demo||!items.length)return;setBusy(true);setError("");const data=new FormData(e.currentTarget);try{const response=await fetch("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:data.get("email"),fullName:`${data.get("firstName")} ${data.get("lastName")}`.trim(),phone:data.get("phone"),address:data.get("address"),city:data.get("city"),state,items:items.map(({id,size,quantity})=>({id,size,quantity}))})});const result=await response.json() as {id?:string;error?:string};if(!response.ok)throw new Error(result.error||"Unable to place order");clear();router.push(`/order-confirmed?id=${encodeURIComponent(result.id||"")}`)}catch(err){setError(err instanceof Error?err.message:"Unable to place order")}finally{setBusy(false)}}
  if(!ready)return <main className="inner-page empty-state"><h1>CHECKOUT</h1><p role="status">Loading your selection…</p></main>;
  if(!items.length)return <main className="inner-page empty-state"><h1>Your bag is empty.</h1><Link className="dark-button" href="/shop">SHOP THE COLLECTION</Link></main>;
  return <main className="checkout-page"><section><span className="eyebrow">VELMORA / ORDER REQUEST</span><h1>CHECKOUT</h1><p>{demo?"Portfolio preview · sample order":"Continue as guest"}</p><form onSubmit={submit}><h2>CONTACT INFORMATION</h2><label>Email address<input name="email" type="email" autoComplete="email" placeholder="you@example.com" required maxLength={160}/></label><h2>SHIPPING DETAILS</h2><div className="form-two"><label>First name<input name="firstName" autoComplete="given-name" required maxLength={80}/></label><label>Last name<input name="lastName" autoComplete="family-name" required maxLength={80}/></label></div><label>Phone number<input name="phone" type="tel" autoComplete="tel" placeholder="+234 803 123 4567" required maxLength={30}/></label><label>Address<input name="address" autoComplete="street-address" required maxLength={160}/></label><div className="form-two"><label>City<input name="city" autoComplete="address-level2" required maxLength={80}/></label><div className="form-select"><span>State</span><Select value={state} onValueChange={setState}><SelectTrigger aria-label="State"><SelectValue/></SelectTrigger><SelectContent>{states.map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select></div></div><h2>DELIVERY</h2><RadioGroup value={state==="Lagos"?"lagos":"other"} className="delivery-options"><label><RadioGroupItem value="lagos" disabled={state!=="Lagos"}/>Standard delivery — Lagos <strong>₦3,500</strong></label><label><RadioGroupItem value="other" disabled={state==="Lagos"}/>Delivery outside Lagos <strong>₦5,500</strong></label></RadioGroup><p className="checkout-notice">This portfolio preview records an order request. No payment is taken. Delivery and payment would be confirmed by a live store team.</p>{error&&<p role="alert" className="field-error">{error}</p>}<button className="dark-button" disabled={busy||demo}>{demo?"PREVIEW ONLY":busy?"PLACING REQUEST...":"PLACE ORDER REQUEST"}</button></form></section><aside className="checkout-summary"><h2>ORDER SUMMARY <small>{items.length} {items.length===1?"ITEM":"ITEMS"}</small></h2>{items.map(i=><div className="summary-product" key={i.id+i.size}><img src={i.image} alt={i.name}/><div><strong>{i.name}</strong><span>{i.color} / {i.size} / Qty {i.quantity}</span></div><strong>{naira(i.price*i.quantity)}</strong></div>)}<div className="summary-line"><span>Subtotal</span><strong>{naira(subtotal)}</strong></div><div className="summary-line"><span>Delivery</span><strong>{naira(deliveryFee)}</strong></div><div className="summary-line total"><span>Total</span><strong>{naira(subtotal+deliveryFee)}</strong></div></aside></main>}
